version: "3.8"

services:
  # סביבת ייצור
  website:
    image: erlichsefi/israeli-grocery-insight:latest
    build:
      context: .
      target: production
    hostname: website
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped

  nginx:
    image: erlichsefi/israeli-grocery-insight-nginx:latest
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=www.openisraelisupermarkets.co.il
      - EMAIL=erlichsefi@gmail.com
    depends_on:
      - website
    restart: unless-stopped

volumes:
  node_modules:
