version: "3.8"

services:
  # סביבת ייצור
  website:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=80
    restart: unless-stopped

volumes:
  node_modules:
