version: "3.8"

services:
  # סביבת ייצור
  website:
    build:
      context: .
      target: production
    hostname: website
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
      - website
    restart: unless-stopped

volumes:
  node_modules:
