name: Deploy to Runner

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: erlichsefi/israeli-grocery-insight

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

      - name: Deploy to Runner
        run: docker stop israeli-grocery-insight || true
          docker rm israeli-grocery-insight || true
          docker run -d \
          --name israeli-grocery-insight \
          --restart unless-stopped \
          -p 8000:8000 \
          ${{ env.DOCKER_IMAGE }}:latest
