name: Deploy to Runner

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: erlichsefi/israeli-grocery-insight

jobs:
  build-and-deploy:
    runs-on: [self-hosted, front-end]

    steps:
      - name: Adding env variables
        run: |
          echo "SUPABASE_URL=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
          echo "SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          echo "Current working directory: $PWD"
          docker compose build
      - name: Deploy to Runner
        run: |
          echo "Current working directory: $PWD"
          docker compose down || true
          docker compose pull
          docker compose up -d
