name: SSL Certificate Management

on:
  schedule:
    - cron: '0 0 1 * *'  # רץ בתחילת כל חודש
  workflow_dispatch:  # מאפשר הפעלה ידנית

jobs:
  ssl-renewal:
    runs-on: [self-hosted, front-end]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-venv libaugeas0

      - name: Remove existing certbot
        run: |
          sudo apt-get remove -y certbot || true
          sudo rm -rf /opt/certbot || true

      - name: Set up Python virtual environment
        run: |
          sudo python3 -m venv /opt/certbot/
          sudo /opt/certbot/bin/pip install --upgrade pip

      - name: Install Certbot
        run: |
          sudo /opt/certbot/bin/pip install certbot certbot-nginx
          sudo ln -sf /opt/certbot/bin/certbot /usr/bin/certbot

      - name: Run Certbot renewal
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          sudo certbot renew --non-interactive --agree-tos -m $EMAIL || true
          
      - name: Set up automatic renewal
        run: |
          echo "0 0,12 * * * root /opt/certbot/bin/python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew -q" | sudo tee -a /etc/crontab > /dev/null

      - name: Verify SSL certificate
        run: |
          curl -I https://${{ secrets.DOMAIN }}
