name: SSL Certificate Management

on:
  schedule:
    - cron: "0 0 1 * *" # רץ בתחילת כל חודש
  workflow_dispatch: # מאפשר הפעלה ידנית

jobs:
  ssl-renewal:
    runs-on: [self-hosted, front-end]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-venv libaugeas0

      - name: Remove existing certbot
        run: |
          sudo apt-get remove -y certbot || true
          sudo rm -rf /opt/certbot || true

      - name: Set up Python virtual environment
        run: |
          sudo python3 -m venv /opt/certbot/
          sudo /opt/certbot/bin/pip install --upgrade pip

      - name: Install Certbot
        run: |
          sudo /opt/certbot/bin/pip install certbot certbot-nginx
          sudo ln -sf /opt/certbot/bin/certbot /usr/bin/certbot

      - name: Create SSL directory
        run: |
          sudo mkdir -p /etc/nginx/ssl
          sudo chmod 755 /etc/nginx/ssl

      - name: Run Certbot
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          sudo certbot certonly --nginx \
            --non-interactive \
            --agree-tos \
            -m $EMAIL \
            -d $DOMAIN \
            --cert-path /etc/nginx/ssl/cert.pem \
            --key-path /etc/nginx/ssl/private.key

      - name: Set permissions
        run: |
          sudo chown -R www-data:www-data /etc/nginx/ssl
          sudo chmod 600 /etc/nginx/ssl/private.key
          sudo chmod 644 /etc/nginx/ssl/cert.pem

      - name: Verify SSL certificate
        run: |
          curl -I https://www.openisraelisupermarkets.co.il

      - name: Reload Nginx
        run: |
          sudo nginx -t && sudo systemctl reload nginx
